export const ItemAssets = {
  "파괴석 조각": "/assets/items/파괴석 조각.png",
  "파괴석": "/assets/items/파괴석.png",
  "파괴석 결정": "/assets/items/파괴석 결정.png",
  "파괴강석": "/assets/items/파괴강석.png",
  "정제된 파괴강석": "/assets/items/정제된 파괴강석.png",
  "운명의 파괴석": "/assets/items/운명의 파괴석.png",
  "수호석 조각": "/assets/items/수호석 조각.png",
  "수호석": "/assets/items/수호석.png",
  "수호석 결정": "/assets/items/수호석 결정.png",
  "수호강석": "/assets/items/수호강석.png",
  "정제된 수호강석": "/assets/items/정제된 수호강석.png",
  "운명의 수호석": "/assets/items/운명의 수호석.png",
  "조화의 돌파석": "/assets/items/조화의 돌파석.png",
  "명예의 돌파석": "/assets/items/명예의 돌파석.png",
  "위대한 명예의 돌파석": "/assets/items/위대한 명예의 돌파석.png",
  "경이로운 명예의 돌파석": "/assets/items/경이로운 명예의 돌파석.png",
  "찬란한 명예의 돌파석": "/assets/items/찬란한 명예의 돌파석.png",
  "운명의 돌파석": "/assets/items/운명의 돌파석.png",
  "오레하 융화 재료": "/assets/items/오레하 융화 재료.png",
  "상급 오레하 융화 재료": "/assets/items/상급 오레하 융화 재료.png",
  "최상급 오레하 융화 재료": "/assets/items/최상급 오레하 융화 재료.png",
  "아비도스 융화 재료": "/assets/items/아비도스 융화 재료.png",
  "조화의 파편 주머니(소)": "/assets/items/조화의 파편 주머니(소).png",
  "명예의 파편 주머니(소)": "/assets/items/명예의 파편 주머니(소).png",
  "운명의 파편 주머니(소)": "/assets/items/운명의 파편 주머니(소).png",
  "조화의 파편 주머니(중)": "/assets/items/조화의 파편 주머니(중).png",
  "명예의 파편 주머니(중)": "/assets/items/명예의 파편 주머니(중).png",
  "조화의 파편 주머니(대)": "/assets/items/조화의 파편 주머니(대).png",
  "명예의 파편 주머니(대)": "/assets/items/명예의 파편 주머니(대).png",
  "운명의 파편 주머니(중)": "/assets/items/운명의 파편 주머니(중).png",
  "별의 숨결": "/assets/items/별의 숨결.png",
  "태양의 은총": "/assets/items/태양의 은총.png",
  "태양의 축복": "/assets/items/태양의 축복.png",
  "태양의 가호": "/assets/items/태양의 가호.png",
  "용암의 숨결": "/assets/items/용암의 숨결.png",
  "빙하의 숨결": "/assets/items/빙하의 숨결.png",
  "재봉술 : 비늘 [5-7]": "/assets/items/재봉술 - 비늘 [5-7].png",
  "재봉술 : 선혈 [8-10]": "/assets/items/재봉술 - 선혈 [8-10].png",
  "재봉술 : 마수 [11-15]": "/assets/items/재봉술 - 마수 [11-15].png",
  "재봉술 : 몽환 [13-15]": "/assets/items/재봉술 - 몽환 [13-15].png",
  "재봉술 : 몽환 [16-19]": "/assets/items/재봉술 - 몽환 [16-19].png",
  "재봉술 : 쇠락 [13-15]": "/assets/items/재봉술 - 쇠락 [13-15].png",
  "재봉술 : 쇠락 [16-19]": "/assets/items/재봉술 - 쇠락 [16-19].png",
  "재봉술 : 업화 [11-14]": "/assets/items/재봉술 - 업화 [11-14].png",
  "야금술 : 비늘 [5-7]": "/assets/items/야금술 - 비늘 [5-7].png",
  "야금술 : 선혈 [8-10]": "/assets/items/야금술 - 선혈 [8-10].png",
  "야금술 : 마수 [11-15]": "/assets/items/야금술 - 마수 [11-15].png",
  "야금술 : 몽환 [13-15]": "/assets/items/야금술 - 몽환 [13-15].png",
  "야금술 : 몽환 [16-19]": "/assets/items/야금술 - 몽환 [16-19].png",
  "야금술 : 쇠락 [13-15]": "/assets/items/야금술 - 쇠락 [13-15].png",
  "야금술 : 쇠락 [16-19]": "/assets/items/야금술 - 쇠락 [16-19].png",
  "야금술 : 업화 [11-14]": "/assets/items/야금술 - 업화 [11-14].png"
};